---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs-system
spec:
  interval: 1m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.11.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  interval: 24h
  values:
    nfs:
      server: unas-pro.prod.lionux.lan
      path: /var/nfs/shared/k8s-storage
