---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: nfs-system
spec:
  interval: 12h
  url: https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts/v4.10.0
