---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: nfs-system
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
